package com.dndtool.offline.rules;

import java.io.IOException;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Map;

/** Independent operator-maintained evidence, never generated by the artifact builder/installer.
 * The protected maintenance directory and the administrator's reports are the trust boundary;
 * hashes detect mixups, and do not authenticate administrators or prove historical truth.
 */
public final class MaintenanceEvidence {
    private final Map<String,Object> config;
    private MaintenanceEvidence(Map<String,Object> config) {this.config=config;}
    public static MaintenanceEvidence read(Path directory) throws IOException {
        try(var root=SecureFiles.directory(directory)) {
            if(java.nio.file.Files.getPosixFilePermissions(directory,java.nio.file.LinkOption.NOFOLLOW_LINKS).stream()
                    .anyMatch(p->p.name().startsWith("GROUP_")||p.name().startsWith("OTHERS_")))
                throw new IOException("Maintenance evidence directory must be owner-only");
            var map=OfflineJson.object(OfflineJson.parse(SecureFiles.read(root,"maintenance.json",16384)),
                    "evidence_version","target","lineage","jdbc_url","user","server_uuid","current_user","grants_sha256",
                    "schema_audit_sha256","history_audit_sha256","isolation_audit_sha256","expires_at","permission",
                    "isolated_operation","history_minimum_version","state_directory");
            if(OfflineJson.number(map,"evidence_version")!=1)throw OfflineJson.bad();
            if(!Path.of(OfflineJson.string(map,"state_directory")).isAbsolute())throw OfflineJson.bad();
            OperationTicket.token(OfflineJson.string(map,"target"));OperationTicket.token(OfflineJson.string(map,"lineage"));
            String url=OfflineJson.string(map,"jdbc_url");
            // A single direct TCP endpoint, fixed source schema, fixed driver safety properties.
            if(!url.matches("jdbc:mysql://127[.]0[.]0[.]1:[1-9][0-9]{0,4}/dnd_tool_rules"))throw OfflineJson.bad();
            int port=Integer.parseInt(url.substring(url.lastIndexOf(':')+1,url.lastIndexOf('/')));
            if(port>65535)throw OfflineJson.bad();
            if(!OfflineJson.string(map,"user").matches("[a-z][a-z0-9_]{0,63}"))throw OfflineJson.bad();
            if(!OfflineJson.string(map,"server_uuid").matches("[0-9a-f-]{36}"))throw OfflineJson.bad();
            if(!OfflineJson.string(map,"current_user").matches("[a-z][a-z0-9_]{0,63}@127[.]0[.]0[.]1"))throw OfflineJson.bad();
            for(String type:new String[]{"schema","history","isolation"}) {
                String hash=OfflineJson.string(map,type+"_audit_sha256");RuleArtifact.digestText(hash);
                byte[] report=SecureFiles.read(root,type+"-audit.txt",65536);
                if(report.length==0 || !RuleArtifact.sha256(report).equals(hash))throw new IOException("Independent audit report mismatch");
            }
            RuleArtifact.digestText(OfflineJson.string(map,"grants_sha256"));
            String permission=OfflineJson.string(map,"permission");
            if(!permission.equals("INSTALL") && !permission.equals("RESOLVE"))throw OfflineJson.bad();
            String isolated=OfflineJson.string(map,"isolated_operation");
            if(!isolated.equals("none")) {
                var uuid=java.util.UUID.fromString(isolated);
                if(uuid.version()!=4 || uuid.variant()!=2 || !uuid.toString().equals(isolated))throw OfflineJson.bad();
            }
            var evidence=new MaintenanceEvidence(Map.copyOf(map));evidence.fresh();return evidence;
        }
    }
    void fresh() {if(!Instant.parse(text("expires_at")).isAfter(Instant.now()))throw new IllegalStateException("Maintenance evidence expired");}
    void requireInstall() {fresh();if(!text("permission").equals("INSTALL"))throw new IllegalStateException("No independent installation authorization");}
    void requireResolution(OperationTicket ticket) {
        match(ticket);fresh();
        if(!text("permission").equals("RESOLVE") || !text("isolated_operation").equals(ticket.operationId().toString()))
            throw new IllegalStateException("Original executor isolation is not independently attested");
    }
    void match(OperationTicket ticket) {if(!target().equals(ticket.target()) || !lineage().equals(ticket.lineage()))throw new IllegalStateException("Source lineage mismatch");}
    String text(String key) {return OfflineJson.string(config,key);}
    public String target() {return text("target");}
    public String lineage() {return text("lineage");}
    long minimumVersion() {return OfflineJson.number(config,"history_minimum_version");}
    String url() {return text("jdbc_url");}
    String user() {return text("user");}
    public Path stateDirectory() {return Path.of(text("state_directory"));}
}
