package com.dndtool.persistence;

import static org.junit.jupiter.api.Assertions.*;

import com.dndtool.module.LanguagePartition;
import com.dndtool.module.ToolCatalogOracle;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Proxy;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.stream.Stream;
import javax.sql.DataSource;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;

/** Strict JDBC protocol tests, not evidence of actual MySQL isolation, privileges or schema health. */
class JdbcSourceLanguageRepositoryTest {
    // Independent handwritten source/expected matrix: never generated by the production mapper.
    private static final List<Expected> MATRIX = List.of(
            new Expected("abyssal", "Abyssal", "EXOTIC", 1),
            new Expected("celestial", "Celestial", "EXOTIC", 2),
            new Expected("common", "Common", "STANDARD", 3),
            new Expected("deep_speech", "Deep Speech", "EXOTIC", 4),
            new Expected("draconic", "Draconic", "EXOTIC", 5),
            new Expected("druidic", "Druidic", "SECRET", 6),
            new Expected("dwarvish", "Dwarvish", "STANDARD", 7),
            new Expected("elvish", "Elvish", "STANDARD", 8),
            new Expected("giant", "Giant", "STANDARD", 9),
            new Expected("gnomish", "Gnomish", "STANDARD", 10),
            new Expected("goblin", "Goblin", "STANDARD", 11),
            new Expected("halfling", "Halfling", "STANDARD", 12),
            new Expected("infernal", "Infernal", "EXOTIC", 13),
            new Expected("orc", "Orc", "STANDARD", 14),
            new Expected("primordial", "Primordial", "EXOTIC", 15),
            new Expected("sylvan", "Sylvan", "EXOTIC", 16),
            new Expected("thieves_cant", "Thieves Cant", "SECRET", 17),
            new Expected("undercommon", "Undercommon", "EXOTIC", 18));
    private static final String HASH = "0123456789abcdef".repeat(4);

    @Test
    void projectsEveryIndependentFieldAndClosesBeforeReturning() throws Exception {
        Fixture fixture = new Fixture();
        LanguagePartition partition = fixture.load();
        assertMatrix(partition);
        fixture.assertCompleted();
        assertThrows(UnsupportedOperationException.class, () -> partition.languages().clear());
        assertEquals(List.of("schema", "ledger", "release", "installation", "partition", "language", "tool"),
                fixture.queries);
        assertEquals(19, fixture.nextCalls.get("language"));
        assertEquals(1, fixture.commits);
        assertEquals(0, fixture.rollbacks);
        assertEquals(0, fixture.aborts);
    }

    @Test
    void rowOrderAndSourceIdsDoNotChangeLogicalOutput() throws Exception {
        Fixture fixture = new Fixture();
        Collections.reverse(fixture.rows.get("language"));
        fixture.setReleaseId(91L);
        assertMatrix(fixture.load());
        fixture.assertCompleted();
    }

    @Test
    void explicitDisplayOrderAndLegalPagesAndTextArePreserved() throws Exception {
        Fixture fixture = new Fixture();
        fixture.language(2).put("sort_order", 4);
        fixture.language(3).put("sort_order", 3);
        fixture.language(2).put("source_page", (short) 3);
        fixture.language(3).put("source_page", (byte) 74);
        fixture.language(2).put("display_name", "\ud83d\udc09".repeat(120));
        fixture.language(2).put("description", "\ud83d\udc09".repeat(1000));
        fixture.language(3).put("display_name", "é");
        LanguagePartition partition = fixture.load();
        assertEquals(4, partition.definitions().get(2).sortOrder());
        assertEquals(3, partition.definitions().get(3).sortOrder());
        assertEquals(3, ((LanguagePartition.SourcePageAttribute) partition.attributes().get(5)).value());
        assertEquals(74, ((LanguagePartition.SourcePageAttribute) partition.attributes().get(7)).value());
        assertEquals("\ud83d\udc09".repeat(120), partition.definitions().get(2).displayName());
        assertEquals("\ud83d\udc09".repeat(1000), partition.definitions().get(2).description());
        assertEquals("é", partition.definitions().get(3).displayName());
    }

    @Test
    void historicalCompleteDigestIsNeitherComparedNorUsedForCurrentAdmission() throws Exception {
        Fixture fixture = new Fixture();
        Map<String, Object> oldComplete = new HashMap<>(fixture.row("installation"));
        oldComplete.put("installation_revision", 1L);
        oldComplete.put("verification_scope", bytes("COMPLETE"));
        oldComplete.put("observed_content_sha256", bytes("a".repeat(64)));
        fixture.history.put(1L, List.of(oldComplete));
        assertMatrix(fixture.load());
        assertEquals(2L, fixture.bindings.get("installation").get(2));
        assertEquals(1, fixture.history.size());
        assertArrayEquals(bytes("a".repeat(64)), (byte[]) oldComplete.get("observed_content_sha256"));

        Fixture missingCurrent = new Fixture();
        missingCurrent.history.put(1L, List.of(oldComplete));
        missingCurrent.rows.get("installation").clear();
        assertRejected(missingCurrent);
    }

    @Test
    void packageDisplayMetadataDoesNotEnterProjection() throws Exception {
        Fixture fixture = new Fixture();
        fixture.row("installation").put("package_display_name", "改名\ud83d\udc09");
        assertMatrix(fixture.load());
    }

    @TestFactory
    Stream<DynamicTest> rejectsMalformedLanguageRowsAndExactSetViolations() {
        List<Case> cases = new ArrayList<>();
        cases.add(new Case("missing", f -> f.rows.get("language").remove(2)));
        cases.add(new Case("duplicate key", f -> f.language(2).put("language_key", bytes("language.abyssal"))));
        cases.add(new Case("fake replacing common", f -> f.language(2).put("language_key", bytes("language.fake"))));
        cases.add(new Case("duplicate order", f -> f.language(2).put("sort_order", 4)));
        cases.add(new Case("cross release", f -> f.language(2).put("release_id", 8L)));
        cases.add(new Case("matrix mismatch", f -> f.language(2).put("category", bytes("SECRET"))));
        for (Object value : List.of(bytes("UNKNOWN"), bytes("standard"), bytes("STANDARD "),
                bytes("STANDARD\0"), new byte[]{(byte) 0xff}, "STANDARD", 8)) {
            cases.add(change("category", value));
        }
        for (Object value : List.of(bytes("language.common "), bytes("Language.common"),
                bytes("language.common\0"), bytes("x".repeat(129)), new byte[]{(byte) 0x80}, "language.common")) {
            cases.add(change("language_key", value));
        }
        for (String column : List.of("source_page", "sort_order", "release_id")) {
            for (Object value : List.of("59", 59.0, new BigDecimal("59"), new BigInteger("59"),
                    true, Long.MIN_VALUE, Long.MAX_VALUE)) {
                cases.add(change(column, value));
            }
        }
        for (int value : List.of(2, 75, 0, -1)) cases.add(change("source_page", value));
        for (int value : List.of(0, 19, -1)) cases.add(change("sort_order", value));
        for (String column : List.of("display_name", "description")) {
            for (Object value : List.of("", " ", "\u00a0", "e\u0301", "\ud800", "\udc00", 3, bytes("text"),
                    "a\0b", "a\nb", "a\tb", "a\rb", "a\u007fb", "a\u0085b", "a\u009fb")) {
                cases.add(change(column, value));
            }
        }
        cases.add(change("display_name", "\ud83d\udc09".repeat(121)));
        cases.add(change("description", "\ud83d\udc09".repeat(1001)));
        for (String column : List.of("release_id", "language_key", "display_name", "description", "category",
                "source_page", "sort_order")) cases.add(change(column, null));
        return cases.stream().map(test -> DynamicTest.dynamicTest(test.name(), () -> {
            Fixture fixture = new Fixture();
            test.edit().accept(fixture);
            assertRejected(fixture);
        }));
    }

    @Test
    void nineteenthRowIsObservedWithoutReadingOrMaterializingItsFields() {
        Fixture fixture = new Fixture();
        fixture.rows.get("language").add(Map.of());
        assertRejected(fixture);
        assertEquals(19, fixture.nextCalls.get("language"));
        assertEquals(18 * 7, fixture.valueReads.get("language"));
        assertEquals(19, fixture.limits.get("language"));
    }

    @TestFactory
    Stream<DynamicTest> rejectsMalformedHeadCurrentEvidenceAndLedger() {
        List<Case> cases = new ArrayList<>();
        for (String table : List.of("schema", "ledger", "release", "installation", "partition")) {
            cases.add(new Case(table + " missing", f -> f.rows.get(table).clear()));
            cases.add(new Case(table + " duplicate", f -> f.rows.get(table).add(new HashMap<>(f.row(table)))));
        }
        for (Object value : List.of(bytes("dnd_tool_se"), bytes("DND_TOOL_RULES"), bytes("dnd_tool_rules "),
                "dnd_tool_rules", new byte[]{(byte) 0x80})) cases.add(change("schema", "schema_name", value));
        cases.add(change("schema", "schema_name", null));
        for (String column : List.of("schema_version", "script_name", "script_sha256")) {
            cases.add(change("ledger", column, null));
        }
        for (Object value : List.of(0, 2, "1", 1.0, new BigDecimal("1"))) {
            cases.add(change("ledger", "schema_version", value));
        }
        cases.add(change("ledger", "script_name", bytes("V001__runtime.sql")));
        cases.add(change("ledger", "script_sha256", bytes(HASH)));
        cases.add(change("ledger", "script_sha256", bytes("A".repeat(64))));
        for (String column : List.of("id", "installation_revision", "canonical_format_version", "archive_format_version")) {
            for (Object value : List.of(0L, -1L, "2", 2.0, new BigDecimal("2"), new BigInteger("9223372036854775808"))) {
                cases.add(change("release", column, value));
            }
            cases.add(change("release", column, null));
        }
        for (String column : List.of("canonical_format_version", "archive_format_version")) {
            cases.add(change("release", column, 1));
            cases.add(change("release", column, 3));
        }
        for (String value : List.of("01", "1.0", "1 ", "va", "vA", "1\0")) {
            cases.add(change("release", "release_version", bytes(value)));
        }
        for (String column : List.of("module_key", "release_version", "hash_algorithm", "release_status")) {
            cases.add(change("release", column, null));
            cases.add(change("release", column, new byte[]{(byte) 0x80}));
        }
        cases.add(change("release", "module_key", bytes("dnd5e2014_srd51_se_v1")));
        cases.add(change("release", "module_key", bytes("dnd5e2014_srd51_se ")));
        cases.add(change("release", "hash_algorithm", bytes("sha-256")));
        cases.add(change("release", "release_status", bytes("RELEASED")));
        cases.add(change("release", "content_sha256", bytes(HASH)));
        cases.add(change("release", "released_at", java.sql.Timestamp.valueOf("2020-01-01 00:00:00")));
        for (String table : List.of("installation", "partition")) {
            cases.add(change(table, "release_id", 8L));
            cases.add(change(table, "installation_revision", 1L));
            cases.add(change(table, "release_id", null));
            cases.add(change(table, "installation_revision", null));
            cases.add(change(table, "installation_revision", "2"));
        }
        for (String column : List.of("operation_fingerprint_version", "author_schema_version", "installation_manifest_version")) {
            for (Object value : List.of(0, 2, "1", 1.0, new BigDecimal("1"))) {
                cases.add(change("installation", column, value));
            }
            cases.add(change("installation", column, null));
        }
        for (String column : List.of("operation_digest_sha256", "installation_manifest_sha256")) {
            for (Object value : List.of(bytes("a".repeat(63)), bytes("a".repeat(65)), bytes("A".repeat(64)),
                    bytes("g".repeat(64)), HASH)) cases.add(change("installation", column, value));
            cases.add(change("installation", column, null));
        }
        for (Object value : List.of(new byte[15], new byte[16], new byte[17], "uuid")) {
            cases.add(change("installation", "source_operation_id", value));
        }
        byte[] badVariant = operationId();
        badVariant[8] = 0;
        cases.add(change("installation", "source_operation_id", badVariant));
        cases.add(change("installation", "source_operation_id", null));
        for (String value : List.of("COMPLETE", "partition", "PARTITION ")) {
            cases.add(change("installation", "verification_scope", bytes(value)));
        }
        cases.add(change("installation", "verification_scope", null));
        cases.add(change("installation", "observed_content_sha256", bytes(HASH)));
        for (Object value : List.of("e\u0301", "\ud800", "\u0085", " ", "\ud83d\udc09".repeat(121), 5)) {
            cases.add(change("installation", "package_display_name", value));
        }
        cases.add(change("installation", "package_display_name", null));
        for (Object value : List.of(bytes("character.unknown"), bytes("character.language "), "character.language")) {
            cases.add(change("partition", "partition_key", value));
        }
        cases.add(change("partition", "partition_key", null));
        return cases.stream().map(test -> DynamicTest.dynamicTest(test.name(), () -> {
            Fixture fixture = new Fixture();
            test.edit().accept(fixture);
            assertRejected(fixture);
        }));
    }

    @TestFactory
    Stream<DynamicTest> closesEveryResourceOnSqlAndResourceFailures() {
        List<String> failures = new ArrayList<>();
        for (String table : List.of("schema", "ledger", "release", "installation", "partition", "language")) {
            for (String operation : List.of("prepare", "maxRows", "timeout", "execute", "next", "rsClose", "stmtClose")) {
                failures.add(operation + ":" + table);
            }
        }
        failures.add("get:language:source_page");
        failures.add("bind:release");
        failures.add("bind:installation");
        return failures.stream().map(point -> DynamicTest.dynamicTest(point, () -> {
            Fixture fixture = new Fixture();
            fixture.failures.add(point);
            SQLException error = assertThrows(SQLException.class, fixture::load);
            assertEquals(point, error.getMessage());
            assertEquals(0, fixture.commits);
            assertEquals(1, fixture.rollbacks);
            fixture.assertCompleted();
        }));
    }

    @Test
    void commitFailureRollsBackBeforeRestorationAndStillFails() {
        Fixture fixture = new Fixture();
        fixture.failures.add("commit");
        assertEquals("commit", assertThrows(SQLException.class, fixture::load).getMessage());
        assertEquals(1, fixture.commits);
        assertEquals(1, fixture.rollbacks);
        assertTrue(fixture.events.indexOf("rollback") < fixture.events.indexOf("restoreAuto"));
        fixture.assertCompleted();
    }

    @Test
    void rollbackFailureNeverRestoresAutoCommitAndAbortsBeforeClose() {
        Fixture fixture = new Fixture();
        fixture.failures.addAll(Set.of("execute:language", "rollback"));
        SQLException error = assertThrows(SQLException.class, fixture::load);
        assertEquals("execute:language", error.getMessage());
        assertEquals("rollback", error.getSuppressed()[0].getMessage());
        assertEquals(1, fixture.aborts);
        assertEquals(1, fixture.closes);
        assertFalse(fixture.events.contains("restoreAuto"));
        assertFalse(fixture.events.contains("restoreIsolation"));
        assertTrue(fixture.events.indexOf("abort") < fixture.events.indexOf("close"));
        fixture.assertResourcesClosed();
    }

    @Test
    void commitAndRollbackFailuresPreserveBothAndNeverImplicitlyCommit() {
        Fixture fixture = new Fixture();
        fixture.failures.addAll(Set.of("commit", "rollback", "abort", "close"));
        SQLException error = assertThrows(SQLException.class, fixture::load);
        assertEquals("commit", error.getMessage());
        assertEquals(List.of("rollback", "abort"),
                Stream.of(error.getSuppressed()).map(Throwable::getMessage).toList());
        assertFalse(fixture.events.contains("restoreAuto"));
        assertEquals(0, fixture.closes);
    }

    @Test
    void failedTerminationAfterRestoreFailureQuarantinesTheBorrowedConnection() {
        Fixture fixture = new Fixture();
        fixture.failures.addAll(Set.of("restoreReadOnly", "abort"));
        SQLException error = assertThrows(SQLException.class, fixture::load);
        assertEquals("restoreReadOnly", error.getMessage());
        assertEquals("abort", error.getSuppressed()[0].getMessage());
        assertEquals(0, fixture.closes);
        assertFalse(fixture.events.contains("restoreAuto"));
    }

    @Test
    void rollbackRethrowingTheSameExceptionDoesNotReplaceTheOriginalFailure() {
        Fixture fixture = new Fixture();
        SQLException same = new SQLException("same provider exception");
        fixture.failureInstances.put("execute:language", same);
        fixture.failureInstances.put("rollback", same);
        assertSame(same, assertThrows(SQLException.class, fixture::load));
        assertEquals(0, same.getSuppressed().length);
        assertEquals(1, fixture.aborts);
        assertEquals(1, fixture.closes);
        assertFalse(fixture.events.contains("restoreAuto"));
    }

    @TestFactory
    Stream<DynamicTest> restoreAndCloseFailuresCannotReturnSuccess() {
        return Stream.of("restoreIsolation", "restoreReadOnly", "restoreAuto", "close")
                .map(point -> DynamicTest.dynamicTest(point, () -> {
                    Fixture fixture = new Fixture();
                    fixture.failures.add(point);
                    assertEquals(point, assertThrows(SQLException.class, fixture::load).getMessage());
                    assertEquals(1, fixture.commits);
                    assertEquals(0, fixture.rollbacks);
                    assertEquals(1, fixture.aborts);
                    assertEquals(1, fixture.closes);
                    fixture.assertResourcesClosed();
                }));
    }

    @TestFactory
    Stream<DynamicTest> configurationAndCaptureFailuresDoNotLeakConnections() {
        return Stream.of("getAuto", "getReadOnly", "getIsolation", "configureReadOnly", "configureIsolation", "begin")
                .map(point -> DynamicTest.dynamicTest(point, () -> {
                    Fixture fixture = new Fixture();
                    fixture.failures.add(point);
                    assertEquals(point, assertThrows(SQLException.class, fixture::load).getMessage());
                    assertEquals(0, fixture.commits);
                    assertEquals(point.equals("begin") ? 1 : 0, fixture.rollbacks);
                    assertEquals(1, fixture.closes);
                    assertTrue(fixture.queries.isEmpty());
                }));
    }

    @Test
    void rejectsBorrowedTransactionWithoutTakingCommitOrRollbackOwnership() {
        Fixture fixture = new Fixture();
        fixture.autoCommit = false;
        assertThrows(SQLException.class, fixture::load);
        assertEquals(0, fixture.commits);
        assertEquals(0, fixture.rollbacks);
        assertEquals(1, fixture.aborts);
        assertEquals(1, fixture.closes);
        assertFalse(fixture.events.contains("restoreAuto"));
        assertTrue(fixture.queries.isEmpty());
    }

    @Test
    void restoresNonDefaultReadOnlyAndIsolationAndPropagatesAcquisitionFailure() throws Exception {
        Fixture fixture = new Fixture();
        fixture.readOnly = true;
        fixture.isolation = Connection.TRANSACTION_SERIALIZABLE;
        assertMatrix(fixture.load());
        assertTrue(fixture.readOnly);
        assertEquals(Connection.TRANSACTION_SERIALIZABLE, fixture.isolation);
        assertTrue(fixture.autoCommit);
        Fixture failed = new Fixture();
        failed.failures.add("acquire");
        assertEquals("acquire", assertThrows(SQLException.class, failed::load).getMessage());
        assertEquals(0, failed.closes);
    }

    private static void assertRejected(Fixture fixture) {
        SQLException error = assertThrows(SQLException.class, fixture::load);
        assertEquals("Invalid source language partition", error.getMessage());
        assertEquals(0, fixture.commits);
        assertEquals(1, fixture.rollbacks);
        fixture.assertCompleted();
    }

    private static void assertMatrix(LanguagePartition partition) {
        assertEquals(18, partition.languages().size());
        assertEquals(18, partition.definitions().size());
        assertEquals(36, partition.attributes().size());
        for (int index = 0; index < MATRIX.size(); index++) {
            Expected expected = MATRIX.get(index);
            var row = partition.languages().get(index);
            String key = "language." + expected.key();
            String description = expected.name() + " is an SRD 5.1 language catalog entry.";
            assertEquals(key, row.languageKey());
            assertEquals(expected.name(), row.displayName());
            assertEquals(description, row.description());
            assertEquals(expected.category(), row.category().name());
            assertEquals(59, row.sourcePage());
            assertEquals(expected.order(), row.sortOrder());
            var definition = partition.definitions().get(index);
            assertEquals("character.language", definition.definitionType());
            assertEquals(key, definition.definitionKey());
            assertEquals(expected.name(), definition.displayName());
            assertEquals(description, definition.description());
            assertEquals(expected.order(), definition.sortOrder());
            var category = assertInstanceOf(LanguagePartition.CategoryAttribute.class, partition.attributes().get(index * 2));
            assertEquals(expected.category(), category.value().name());
            assertEquals("catalog.category", category.attributeKey());
            assertEquals("IDENTIFIER", category.valueType());
            var page = assertInstanceOf(LanguagePartition.SourcePageAttribute.class, partition.attributes().get(index * 2 + 1));
            assertEquals(59, page.value());
            assertEquals("source.page", page.attributeKey());
            assertEquals("INTEGER", page.valueType());
            for (var attribute : List.of(category, page)) {
                assertEquals("character.language", attribute.definitionType());
                assertEquals(key, attribute.definitionKey());
                assertEquals(1, attribute.attributeOrder());
            }
        }
    }

    private static Case change(String column, Object value) {
        return new Case("language " + column + " " + String.valueOf(value), f -> f.language(2).put(column, value));
    }

    private static Case change(String table, String column, Object value) {
        return new Case(table + " " + column + " " + String.valueOf(value), f -> f.row(table).put(column, value));
    }

    private static byte[] bytes(String value) { return value.getBytes(StandardCharsets.US_ASCII); }
    private static byte[] operationId() {
        byte[] value = new byte[16];
        value[6] = 0x40;
        value[8] = (byte) 0x80;
        return value;
    }

    private record Expected(String key, String name, String category, int order) {}
    private record Case(String name, Consumer<Fixture> edit) {}

    private static final class Fixture {
        final Map<String, List<Map<String, Object>>> rows = new LinkedHashMap<>();
        final Map<Long, List<Map<String, Object>>> history = new HashMap<>();
        final Map<String, Map<Integer, Object>> bindings = new HashMap<>();
        final Map<String, Integer> limits = new HashMap<>();
        final Map<String, Integer> nextCalls = new HashMap<>();
        final Map<String, Integer> valueReads = new HashMap<>();
        final List<String> queries = new ArrayList<>();
        final List<String> events = new ArrayList<>();
        final Set<String> failures = new java.util.HashSet<>();
        final Map<String, SQLException> failureInstances = new HashMap<>();
        final List<Resource> statements = new ArrayList<>();
        final List<Resource> results = new ArrayList<>();
        boolean autoCommit = true;
        boolean readOnly;
        int isolation = Connection.TRANSACTION_READ_COMMITTED;
        int commits;
        int rollbacks;
        int aborts;
        int closes;
        long releaseId = 7L;
        final Connection connection = proxy(Connection.class, this::connectionCall);

        Fixture() {
            rows.put("schema", one("schema_name", bytes("dnd_tool_rules")));
            rows.put("ledger", one("schema_version", 1, "script_name", bytes("V001__rule-source-schema.sql"),
                    "script_sha256", bytes("003916bc758315351e46f177fec10eb70f2b1275a524d270c6eb89a602cd130e")));
            rows.put("release", one("id", releaseId, "module_key", bytes("dnd5e2014_srd51_se"), "release_version", bytes("1"),
                    "canonical_format_version", 2, "archive_format_version", 2, "hash_algorithm", bytes("SHA-256"),
                    "content_sha256", null, "release_status", bytes("DRAFT"), "installation_revision", 2L, "released_at", null));
            rows.put("installation", one("release_id", releaseId, "installation_revision", 2L, "source_operation_id", operationId(),
                    "operation_fingerprint_version", 1, "operation_digest_sha256", bytes(HASH), "author_schema_version", 1,
                    "installation_manifest_version", 1, "installation_manifest_sha256", bytes(HASH), "package_display_name", "SRD Languages",
                    "verification_scope", bytes("PARTITION"), "observed_content_sha256", null));
            rows.put("partition", one("release_id", releaseId, "installation_revision", 2L, "partition_key", bytes("character.language")));
            List<Map<String, Object>> languages = new ArrayList<>();
            for (Expected row : MATRIX) {
                languages.add(one("release_id", releaseId, "language_key", bytes("language." + row.key()),
                        "display_name", row.name(), "description", row.name() + " is an SRD 5.1 language catalog entry.",
                        "category", bytes(row.category()), "source_page", 59, "sort_order", row.order()).get(0));
            }
            rows.put("language", languages);
            var migration=RuleSchemaMigrations.expectations().get(1);
            rows.get("ledger").add(one("schema_version",2,"script_name",bytes(migration.scriptName()),"script_sha256",bytes(migration.scriptSha256())).get(0));
            rows.get("partition").add(one("release_id",releaseId,"installation_revision",2L,"partition_key",bytes("character.tool")).get(0));
            rows.put("tool",new ArrayList<>(ToolCatalogOracle.rows().stream().map(t->one("release_id",releaseId,
                    "tool_key",bytes(t.key()),"display_name",t.name(),"description",t.description(),"category",bytes(t.category()),
                    "source_page",t.page(),"sort_order",t.order()).get(0)).toList()));
        }

        LanguagePartition load() throws SQLException {
            DataSource source = proxy(DataSource.class, (object, method, arguments) -> {
                if (method.getName().equals("getConnection") && (arguments == null || arguments.length == 0)) {
                    hit("acquire");
                    return connection;
                }
                throw unexpected(method.getName());
            });
            return new JdbcSourceLanguageRepository(source).load();
        }

        Map<String, Object> row(String table) { return rows.get(table).get(0); }
        Map<String, Object> language(int index) { return rows.get("language").get(index); }

        void setReleaseId(long id) {
            releaseId = id;
            row("release").put("id", id);
            row("installation").put("release_id", id);
            rows.get("partition").forEach(row->row.put("release_id",id));
            rows.get("tool").forEach(row->row.put("release_id",id));
            rows.get("language").forEach(row -> row.put("release_id", id));
        }

        Object connectionCall(Object object, java.lang.reflect.Method method, Object[] args) throws Throwable {
            return switch (method.getName()) {
                case "getAutoCommit" -> { hit("getAuto"); yield autoCommit; }
                case "isReadOnly" -> { hit("getReadOnly"); yield readOnly; }
                case "getTransactionIsolation" -> { hit("getIsolation"); yield isolation; }
                case "setReadOnly" -> {
                    hit(events.contains("configureReadOnly") ? "restoreReadOnly" : "configureReadOnly");
                    readOnly = (boolean) args[0]; yield null;
                }
                case "setTransactionIsolation" -> {
                    hit(events.contains("configureIsolation") ? "restoreIsolation" : "configureIsolation");
                    isolation = (int) args[0]; yield null;
                }
                case "setAutoCommit" -> {
                    boolean value = (boolean) args[0];
                    hit(value ? "restoreAuto" : "begin");
                    if (value) assertTrue(autoCommit || commits > 0 && !failures.contains("commit")
                            || rollbacks > 0 && !failures.contains("rollback"), "implicit commit of unresolved transaction");
                    autoCommit = value; yield null;
                }
                case "prepareStatement" -> {
                    assertEquals(1, args.length);
                    assertFalse(autoCommit);
                    assertTrue(readOnly);
                    assertEquals(Connection.TRANSACTION_REPEATABLE_READ, isolation);
                    String table = table((String) args[0]);
                    hit("prepare:" + table);
                    queries.add(table);
                    yield statement(table);
                }
                case "commit" -> { commits++; hit("commit"); assertResourcesClosed(); yield null; }
                case "rollback" -> { rollbacks++; hit("rollback"); assertResourcesClosed(); yield null; }
                case "abort" -> { aborts++; hit("abort"); yield null; }
                case "close" -> { closes++; hit("close"); yield null; }
                default -> throw unexpected(method.getName());
            };
        }

        PreparedStatement statement(String table) {
            Resource resource = new Resource();
            statements.add(resource);
            Map<Integer, Object> parameters = new HashMap<>();
            bindings.put(table, parameters);
            return proxy(PreparedStatement.class, (object, method, args) -> {
                assertFalse(resource.closed);
                return switch (method.getName()) {
                    case "setMaxRows" -> {
                        hit("maxRows:" + table);
                        int maximum = (int) args[0];
                        assertEquals(table.equals("language") ? 19 : table.equals("tool") ? 38 : Set.of("ledger","partition").contains(table) ? 3 : 2, maximum);
                        limits.put(table, maximum); yield null;
                    }
                    case "setQueryTimeout" -> {
                        hit("timeout:" + table); assertEquals(5, args[0]); resource.timeout = true; yield null;
                    }
                    case "setBytes", "setLong" -> {
                        hit("bind:" + table); parameters.put((int) args[0], args[1]); yield null;
                    }
                    case "executeQuery" -> {
                        assertTrue(resource.timeout);
                        assertTrue(limits.containsKey(table));
                        assertParameters(table, parameters);
                        hit("execute:" + table);
                        List<Map<String, Object>> selected = rows.get(table);
                        if (table.equals("installation") && !Long.valueOf(2).equals(parameters.get(2))) {
                            selected = history.getOrDefault(parameters.get(2), List.of());
                        }
                        yield result(table, selected, resource);
                    }
                    case "close" -> {
                        resource.closed = true; hit("stmtClose:" + table); yield null;
                    }
                    default -> throw unexpected(method.getName());
                };
            });
        }

        ResultSet result(String table, List<Map<String, Object>> selected, Resource statement) {
            Resource resource = new Resource();
            results.add(resource);
            int[] cursor = {-1};
            return proxy(ResultSet.class, (object, method, args) -> {
                assertFalse(statement.closed);
                assertFalse(resource.closed);
                return switch (method.getName()) {
                    case "next" -> {
                        nextCalls.merge(table, 1, Integer::sum);
                        hit("next:" + table);
                        cursor[0]++;
                        yield cursor[0] < Math.min(selected.size(), limits.get(table));
                    }
                    case "getObject" -> {
                        assertEquals(1, args.length);
                        Map<String, Object> current = selected.get(cursor[0]);
                        assertTrue(current.containsKey(args[0]), "unknown selected column " + args[0]);
                        valueReads.merge(table, 1, Integer::sum);
                        hit("get:" + table + ":" + args[0]);
                        yield current.get(args[0]);
                    }
                    case "close" -> {
                        resource.closed = true; hit("rsClose:" + table); yield null;
                    }
                    default -> throw unexpected(method.getName());
                };
            });
        }

        void assertParameters(String table, Map<Integer, Object> parameters) {
            if (table.equals("release")) {
                assertEquals(Set.of(1, 2), parameters.keySet());
                assertArrayEquals(bytes("dnd5e2014_srd51_se"), (byte[]) parameters.get(1));
                assertArrayEquals(bytes("1"), (byte[]) parameters.get(2));
            } else if (Set.of("installation", "partition").contains(table)) {
                assertEquals(Map.of(1, releaseId, 2, 2L), parameters);
            } else if (Set.of("language","tool").contains(table)) {
                assertEquals(Map.of(1, releaseId), parameters);
            } else assertTrue(parameters.isEmpty());
        }

        void hit(String operation) throws SQLException {
            events.add(operation);
            if (failureInstances.containsKey(operation)) throw failureInstances.get(operation);
            if (failures.contains(operation)) throw new SQLException(operation);
        }

        void assertCompleted() {
            assertTrue(autoCommit);
            assertFalse(readOnly);
            assertEquals(Connection.TRANSACTION_READ_COMMITTED, isolation);
            assertEquals(1, closes);
            assertResourcesClosed();
        }

        void assertResourcesClosed() {
            statements.forEach(resource -> assertTrue(resource.closed));
            results.forEach(resource -> assertTrue(resource.closed));
        }
    }

    private static String table(String sql) {
        // An exact independent SELECT allowlist also forbids DML/DDL, lock reads, old catalogs,
        // cross-schema fallback, dynamic SQL and accidental whole-history scans.
        return switch (sql.replaceAll("\\s+", " ").trim()) {
            case "SELECT CAST(DATABASE() AS BINARY) AS schema_name" -> "schema";
            case "SELECT schema_version, script_name, script_sha256 FROM rule_schema_meta ORDER BY schema_version ASC" -> "ledger";
            case "SELECT id, module_key, release_version, canonical_format_version, archive_format_version, hash_algorithm, content_sha256, release_status, installation_revision, released_at FROM rule_release WHERE module_key = ? AND release_version = ?" -> "release";
            case "SELECT release_id, installation_revision, source_operation_id, operation_fingerprint_version, operation_digest_sha256, author_schema_version, installation_manifest_version, installation_manifest_sha256, package_display_name, verification_scope, observed_content_sha256 FROM rule_package_installation WHERE release_id = ? AND installation_revision = ?" -> "installation";
            case "SELECT release_id, installation_revision, partition_key FROM rule_package_installation_partition WHERE release_id = ? AND installation_revision = ? ORDER BY partition_key" -> "partition";
            case "SELECT release_id, language_key, display_name, description, category, source_page, sort_order FROM rule_language WHERE release_id = ? ORDER BY language_key" -> "language";
            case "SELECT release_id, tool_key, display_name, description, category, source_page, sort_order FROM rule_tool WHERE release_id = ? ORDER BY tool_key" -> "tool";
            default -> throw new AssertionError("Unapproved SQL: " + sql);
        };
    }

    private static List<Map<String, Object>> one(Object... pairs) {
        Map<String, Object> row = new LinkedHashMap<>();
        for (int index = 0; index < pairs.length; index += 2) row.put((String) pairs[index], pairs[index + 1]);
        return new ArrayList<>(List.of(row));
    }

    private static AssertionError unexpected(String method) { return new AssertionError("Unexpected JDBC call: " + method); }

    private static <T> T proxy(Class<T> type, InvocationHandler handler) {
        return type.cast(Proxy.newProxyInstance(type.getClassLoader(), new Class<?>[]{type}, handler));
    }

    private static final class Resource { boolean closed; boolean timeout; }
}
